# Generated by Django 2.2.5 on 2019-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('active_ingredient', models.CharField(max_length=256)),
                ('applicant_name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('manufacturer', models.CharField(max_length=256)),
                ('date_approv', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('reg_no', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Drugs',
            },
        ),
    ]
